import { Vehicle, VehicleStatus } from './types';

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'TOW-001',
    status: VehicleStatus.ACTIVE,
    providerName: 'QuickFix Towing',
    driverName: 'Mike',
    lat: 40.7128,
    lng: -74.0060,
    rating: 4.9,
  },
  {
    id: 'TOW-002',
    status: VehicleStatus.BUSY,
    providerName: 'AAA Official Rescue',
    driverName: 'Sarah',
    lat: 40.7300,
    lng: -74.0500,
    rating: 4.8,
  },
  {
    id: 'TOW-003',
    status: VehicleStatus.ACTIVE,
    providerName: "Zhang's Garage",
    driverName: 'Zhang',
    lat: 40.8000,
    lng: -73.9500,
    rating: 4.5,
  },
  {
    id: 'TOW-004',
    status: VehicleStatus.ACTIVE,
    providerName: 'Brooklyn Best Tow',
    driverName: 'Tony',
    lat: 40.6782,
    lng: -73.9442,
    rating: 4.7,
  },
  {
    id: 'TOW-005',
    status: VehicleStatus.OFFLINE,
    providerName: 'Queens Rapid Response',
    driverName: 'Peter',
    lat: 40.7282,
    lng: -73.7949,
    rating: 4.2,
  },
  {
    id: 'TOW-006',
    status: VehicleStatus.ACTIVE,
    providerName: 'Staten Island Rescue',
    driverName: 'Vinny',
    lat: 40.5795,
    lng: -74.1502,
    rating: 4.6,
  },
  {
    id: 'TOW-007',
    status: VehicleStatus.BUSY,
    providerName: 'Bronx Heavy Duty',
    driverName: 'Marcus',
    lat: 40.8448,
    lng: -73.8648,
    rating: 4.4,
  },
  {
    id: 'TOW-008',
    status: VehicleStatus.ACTIVE,
    providerName: 'Manhattan Elite',
    driverName: 'Jessica',
    lat: 40.7831,
    lng: -73.9712,
    rating: 5.0,
  },
  {
    id: 'TOW-009',
    status: VehicleStatus.OFFLINE,
    providerName: 'Jersey City Haul',
    driverName: 'Bill',
    lat: 40.7178,
    lng: -74.0431,
    rating: 4.3,
  },
  {
    id: 'TOW-010',
    status: VehicleStatus.ACTIVE,
    providerName: 'Newark Tow Masters',
    driverName: 'Jamal',
    lat: 40.7357,
    lng: -74.1724,
    rating: 4.1,
  },
  {
    id: 'TOW-011',
    status: VehicleStatus.BUSY,
    providerName: 'Hoboken Hook',
    driverName: 'Alex',
    lat: 40.7440,
    lng: -74.0324,
    rating: 4.8,
  },
  {
    id: 'TOW-012',
    status: VehicleStatus.ACTIVE,
    providerName: 'Long Island Express',
    driverName: 'Ken',
    lat: 40.7400,
    lng: -73.6000,
    rating: 4.6,
  },
  {
    id: 'TOW-013',
    status: VehicleStatus.ACTIVE,
    providerName: 'Yonkers Yellow Truck',
    driverName: 'Luis',
    lat: 40.9312,
    lng: -73.8987,
    rating: 4.5,
  },
  {
    id: 'TOW-014',
    status: VehicleStatus.OFFLINE,
    providerName: 'Greenwich Village Tow',
    driverName: 'Emily',
    lat: 40.7336,
    lng: -74.0027,
    rating: 4.9,
  },
  {
    id: 'TOW-015',
    status: VehicleStatus.ACTIVE,
    providerName: 'Harlem Night Shift',
    driverName: 'Tyrone',
    lat: 40.8116,
    lng: -73.9465,
    rating: 4.7,
  },
  {
    id: 'TOW-016',
    status: VehicleStatus.BUSY,
    providerName: 'Astoria Auto Aid',
    driverName: 'Dimitri',
    lat: 40.7644,
    lng: -73.9235,
    rating: 4.4,
  },
  {
    id: 'TOW-017',
    status: VehicleStatus.ACTIVE,
    providerName: 'Flushing Flatbed',
    driverName: 'Wei',
    lat: 40.7674,
    lng: -73.8331,
    rating: 4.3,
  },
  {
    id: 'TOW-018',
    status: VehicleStatus.ACTIVE,
    providerName: 'Red Hook Recovery',
    driverName: 'Sam',
    lat: 40.6734,
    lng: -74.0083,
    rating: 4.8,
  },
  {
    id: 'TOW-019',
    status: VehicleStatus.OFFLINE,
    providerName: 'Williamsburg Wheels',
    driverName: 'Hip',
    lat: 40.7126,
    lng: -73.9600,
    rating: 4.2,
  },
  {
    id: 'TOW-020',
    status: VehicleStatus.BUSY,
    providerName: 'Midtown Mechanics',
    driverName: 'Rock',
    lat: 40.7549,
    lng: -73.9840,
    rating: 4.9,
  },
];
